### ISSUE TITLE
✨Sign up page

### ISSUE THREAD

**Issue by mauricenyanja** [Team-folio/TeamFolio#27]
## Summary
This should be a sign-up page that will allow me as a user to sign up

### Screenshot
![Screenshot from 2023-08-18 20-20-51](https://github.com/Team-folio/TeamFolio/assets/68531415/51ebd5c0-a71c-4e64-9de0-bf6b58f4e2a0)
### Acceptance criteria
1. Should be pixel perfect
2. Should match the designs
3. Icons should be

**Comment by VhugoJc** [comment]
Hey! Can I get assigned?
