### ISSUE TITLE
✨Log In/Sign In

### ISSUE THREAD

**Issue by mauricenyanja** [Team-folio/TeamFolio#28]
## Summary
This should be the login or sign in page

### Basic example
![Screenshot from 2023-08-18 20-22-38](https://github.com/Team-folio/TeamFolio/assets/68531415/bd94d459-7e88-4fd3-b3ad-87c64c8b92d9)

### Acceptance criteria
should be pixel perfect to be accepted

**Comment by Sky-De** [comment]
@mauricenyanja hi, please assign this to me, i would like to work on this but let me know is there any image file for your design background image?

**Comment by mauricenyanja** [comment]
Hello  👋 @Sky-De pick it and there is no image just create yours

**Comment by mauricenyanja** [comment]
and fork iy for easier contribution thanks
